permissions:
  contents: read
  id-token: write
on:
  push:
    branches:
      - main
concurrency:
  group: prod
  cancel-in-progress: false
name: prod
jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    env:
      SERVICE: ${{ vars.SERVICE }}
      STAGE: prod
      CDK_DEFAULT_REGION: ${{ vars.CDK_DEFAULT_REGION }}
      CDK_DEFAULT_ACCOUNT: ${{ vars.CDK_DEFAULT_ACCOUNT }}
    name: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.100
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.CDK_DEFAULT_ACCOUNT }}:role/github-actions
          role-duration-seconds: 900
          aws-region: ${{ env.CDK_DEFAULT_REGION }}
      - name: Run cdk deploy
        run: npx cdk deploy ${{ env.SERVICE }}-${{ env.STAGE }}-app --require-approval never
